### ISSUE TITLE
Hydra with ray_aws launcher fails when using hydra_gen_images.py

### ISSUE THREAD

**Issue by lbignone** [lbignone/stylegan3#1]
When using [hydra_gen_images.py](https://github.com/lbignone/stylegan3/blob/cbb5b403142bb8f64366ccea94a5c07f22c40915/hydra_gen_images.py) Ii am getting a `ModuleNotFoundError: No module named 'gen_images'`. 

I think this might be related with using a click callback and cloudpickle together because, locally, the code seems to work fine.

```
Traceback (most recent call last):
  File "/tmp/tmp.uA1oo8n0q4/_remote_invoke.py", line 88, in <module>
    launch_jobs(sys.argv[1])
  File "/tmp/tmp.uA1oo8n0q4/_remote_invoke.py", line 32, in launch_jobs
    job_spec = pickle.load(f)  # nosec
ModuleNotFoundError: No module named 'gen_images'
Shared connection to 54.208.235.169 closed.
Traceback (most recent call last):
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 178, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/hydra_plugins/hydra_ray_launcher/ray_aws_launcher.py", line 62, in launch
    return _core_aws.launch(
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/hydra_plugins/hydra_ray_launcher/_core_aws.py", line 107, in launch
    return launch_jobs(
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/hydra_plugins/hydra_ray_launcher/_core_aws.py", line 155, in launch_jobs
    sdk.run_on_cluster(
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/ray/autoscaler/sdk/sdk.py", line 107, in run_on_cluster
    return commands.exec_cluster(
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 1085, in exec_cluster
    result = _exec(
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 1143, in _exec
    return updater.cmd_runner.run(
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/ray/autoscaler/_private/command_runner.py", line 674, in run
    return self.ssh_command_runner.run(
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/ray/autoscaler/_private/command_runner.py", line 564, in run
    return self._run_helper(final_cmd, with_output, exit_on_fail, silent=silent)
  File "/home/lbignone/.conda/envs/stylegan3_fork/lib/python3.9/site-packages/ray/autoscaler/_private/command_runner.py", line 483, in _run_helper
    raise click.ClickException(
click.exceptions.ClickException: Command failed:

  ssh -tt -i /home/lbignone/.ssh/hydra-lbignone.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_8d659c6347/399189e3e9/%C -o ControlPersist=10s -o ConnectTimeout=120s ec2-user@54.208.235.169 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  stylegan3_ray /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (python /tmp/tmp.uA1oo8n0q4/_remote_invoke.py /tmp/tmp.uA1oo8n0q4)'"'"'"'"'"'"'"'"''"'"' )'

```

**Comment by lbignone** [comment]
I now think that the issue is that running in a docker image is not fully supported/tested. Documentation and examples are missing.

Also, the same exact python versions are required in the local and remote environments. They are handling this by setting up a conda environment by default, but I have disabled that because my setup is different.
